  version: "3.9"

  services:
    db:
      image: postgres
      container_name: ecommercedb
      restart: always
      ports:      
        - "5433:5432"
      environment:
        POSTGRES_DB: ecommerce
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: postgres
      volumes:
        - local_pgdata:/var/lib/postgresql/data

    pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin4_container
      restart: always
      ports:
        - "8888:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: fastapi@admin.com
        PGADMIN_DEFAULT_PASSWORD: postgres
      volumes:
        - pgadmin-data:/var/lib/pgadmin

    mongo:
      image: mongo
      container_name: mongodb
      restart: always
      ports:
        - "27018:27017"

    datafastapi:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8001:8001"
      environment:
        MONGO_URI: "mongodb://mongo:27017/"
      depends_on:
        - mongo

  volumes:
    local_pgdata:
    pgadmin-data:












